version: "3"

networks:
  mynet:
    #检查是否有名为mynet的自定义网络，没有就报错
    external: true

services:
  #如果本地自定义镜像没上传网络或者在某些服务器启用指定容器可以用--profile选项指定启用
  local_php:
    image: $PHP_IMAGE:$PHP_TAG
    container_name: $PHP_CONTAINER_NAME
    restart: unless-stopped
    networks:
      - mynet
    ports:
    - 9000:9000
    volumes:
      - $DOCKER_DATA_DIR/php/$PHP_TAG/php:/usr/local/etc/php
    #使用本地镜像
    build:
      #dockerfile目录
      context: ./dockerfile
      #dockerfile文件名，不加这个参数使用默认名
      dockerfile: php

