version: "3.5"

networks:
  mynet:
    #检查是否有名为mynet的自定义网络，没有就报错
    external: true
volumes:
  mysql:
    name: $MYSQL_VOLUME
  redis:
    name: $REDIS_VOLUME

services:
  php:
    image: $PHP_IMAGE:$PHP_TAG
    container_name: $PHP_CONTAINER_NAME
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - $PHP_PORT:9000
    environment:
      DOCUMENT_ROOT: $PHP_DOCUMENT_ROOT
    volumes:
      - $DOCKER_DATA_DIR/logs/$PHP_TAG/php:/var/log/php
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php:/usr/local/etc/php
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php-fpm.d:/usr/local/etc/php-fpm.d
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - $DOCUMENT_ROOT:$PHP_DOCUMENT_ROOT
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  php8:
    image: $PHP_IMAGE:$PHP_TAG
    container_name: $PHP_CONTAINER_NAME
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - $PHP_PORT:9000
    environment:
      DOCUMENT_ROOT: $PHP_DOCUMENT_ROOT
    volumes:
      - $DOCKER_DATA_DIR/logs/$PHP_TAG/php:/var/log/php
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php:/usr/local/etc/php
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php-fpm.d:/usr/local/etc/php-fpm.d
      - $DOCKER_DATA_DIR/$PHP_IMAGE/$PHP_TAG/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - $DOCUMENT_ROOT:$PHP_DOCUMENT_ROOT
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime    


  nginx:
    image: $NGINX_IMAGE:$NGINX_TAG
    container_name: $NGINX_CONTAINER_NAME
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - 80:80
    volumes:
      - $DOCUMENT_ROOT:$NGINX_DOCUMENT_ROOT
      - $DOCKER_DATA_DIR/logs/$NGINX_TAG/nginx:/var/log/nginx:rw
      - $DOCKER_DATA_DIR/$NGINX_IMAGE/$NGINX_TAG/conf.d:/etc/nginx/conf.d
      - $DOCKER_DATA_DIR/$NGINX_IMAGE/$NGINX_TAG/nginx.conf:/etc/nginx/nginx.conf
      - $DOCKER_DATA_DIR/$NGINX_IMAGE/$NGINX_TAG/fastcgi.conf:/etc/nginx/fastcgi.conf
      - $DOCKER_DATA_DIR/$NGINX_IMAGE/$NGINX_TAG/fastcgi_params:/etc/nginx/fastcgi_params
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime


  mysql:
    image: $MYSQL_IMAGE:$MYSQL_TAG
    container_name: $MYSQL_CONTAINER_NAME
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PWD
    volumes:
        - mysql:/var/lib/mysql:rw
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
        - $DOCKER_DATA_DIR/$MYSQL_IMAGE/$MYSQL_TAG/my.cnf:/etc/mysql/my.cnf:ro


  redis:
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - $DOCKER_DATA_DIR/$REDIS_IMAGE/$REDIS_TAG/redis.conf:/etc/redis.conf:ro
      - redis:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - mynet