ARG ORIGIN_PHP_IMAGE=php
ARG ORIGIN_PHP_TAG=7.3.29-fpm-alpine
FROM ${ORIGIN_PHP_IMAGE}:${ORIGIN_PHP_TAG}
ARG DOCUMENT_ROOT=/var
#扩展
ARG PHP_EXTENSIONS=bcmath,zip,pdo_mysql,mysqli,mbstring,gd,curl,pcntl,redis,rdkafka,imagick
#时区
ARG TZ=UTC
# 仓库源 maybe 加环境判断切换内网源
ARG CONTAINER_PACKAGE_URL=mirrors.tencent.com
RUN sed -i "s/dl-cdn.alpinelinux.org/${CONTAINER_PACKAGE_URL}/g" /etc/apk/repositories
RUN mkdir -p /var/log/php


# 修复DNS问题
# RUN echo nameserver 8.8.8.8 > /etc/resolv.conf

# 安装扩展
COPY ./extensions /tmp/extensions
WORKDIR /tmp/extensions
RUN chmod +x install.sh \
    && sh install.sh \
    && rm -rf /tmp/extensions

ADD ./extensions/install-php-extensions  /usr/local/bin/
#ADD php.ini /usr/local/etc/php/php.ini
#ADD php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

RUN chmod uga+x /usr/local/bin/install-php-extensions

RUN apk --no-cache add tzdata \
    && cp "/usr/share/zoneinfo/$TZ" /etc/localtime \
    && echo "$TZ" > /etc/timezone


# Fix: https://github.com/docker-library/php/issues/240
RUN apk add gnu-libiconv libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php


# Install composer and change it's cache home
RUN curl -o /usr/bin/composer https://mirrors.aliyun.com/composer/composer.phar \
    && chmod +x /usr/bin/composer
ENV COMPOSER_HOME=/tmp/composer

# php image's www-data user uid & gid are 82, change them to 1000 (primary user) 这里有个坑，老项目权限有问题，exec进镜像的时候用root规避
#RUN apk --no-cache add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data
RUN apk --no-cache add curl

EXPOSE 9000

WORKDIR $DOCUMENT_ROOT
